### ISSUE TITLE
Create test validating against GML schema

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-pipelineml10#2]
Schemas are here:
http://schemas.opengis.net/pipelineml/

Here is the standard:
https://www.opengeospatial.org/standards/pipelineml

**Comment by dstenger** [comment]
We need more information to create a first test:
1. Can you provide an example file to be tested?
1. In http://schemas.opengis.net/pipelineml/ I do not find a complete application schema but just dictionaries.
1. Specification mandates GML 3.3 but the provided dictionaries are in GML 3.2. -> Schemas are not conform to spec.

Maybe, we should also think about implementing a general GML application schema test suite which takes the GML application schema as input parameter.

**Comment by johntisdale** [comment]
Here is the official PipelineML schema.
[component_v1-0.zip](https://github.com/opengeospatial/ets-pipelineml10/files/3940979/component_v1-0.zip)

**Comment by johntisdale** [comment]
A set of sample PipelineML files:
[PMLSampleFiles.zip](https://github.com/opengeospatial/ets-pipelineml10/files/3941321/PMLSampleFiles.zip)

**Comment by dstenger** [comment]
@johntisdale Thank you for providing the information.

@keshav-nangare 
Can you please implement a first test which is doing a schema validation against the schema provided in https://github.com/opengeospatial/ets-pipelineml10/issues/2#issuecomment-563347758?
You can use sample data provided in https://github.com/opengeospatial/ets-pipelineml10/issues/2#issuecomment-563386218 for testing.
Currently, the test suite is just a TestNG test suite skeleton. Thus, there might also be changes necessary in the general configuration of the test suite.
Please do not hesitate to do any general changes as the skeleton was created from scratch (see #1) and your changes cannot break anything.
If you have questions or if you need any help, please contact me.

**Comment by dstenger** [comment]
Good example how to implement test: https://github.com/opengeospatial/ets-gml32/blob/master/src/main/java/org/opengis/cite/iso19136/data/XMLSchemaValidationTests.java

**Comment by keshavnangare** [comment]
Fixed with #9 PR.
